// Platform-specific configurations for the Content Generator

export const PLATFORMS = {
  facebook: {
    name: "Facebook",
    slug: "facebook",
    icon: "public",
    gradient: "from-blue-600 to-blue-400",
    accentColor: "blue",
    tagline: "Create highly effective Facebook posts tailored to your specific needs and audience.",
    apiEndpoint: "https://maya-backend-service-326007673689.asia-southeast1.run.app/api/content/facebook/fb_prime",
    fields: [
      { key: "postGoal", label: "Post Goal", hint: "What do you want to achieve?", apiKey: "postGoal",
        options: ["Engagement", "Awareness", "Lead Generation", "Website Traffic", "Conversions", "Brand Loyalty", "Community Building", "Product Promotion", "Event Promotion"] },
      { key: "NicheIndustry", label: "Niche / Industry", hint: "Which industry does your content relate to?", apiKey: "niche",
        options: ["Business", "News", "Technology", "Lifestyle", "Health & Wellness", "Finance", "Education", "Travel", "Food & Beverage", "Sports", "Entertainment", "Real Estate", "Fashion & Beauty", "Parenting", "Non-Profit / Causes"] },
      { key: "PostType", label: "Post Type", hint: "What format will your post take?", apiKey: "postType",
        options: ["Text Post", "Image Post", "Video Post", "Story", "Live Stream", "Link Post", "Event", "Poll / Question"] },
      { key: "ToneStyle", label: "Tone & Style", hint: "What tone should your content have?", apiKey: "toneAndStyle",
        options: ["Informative", "Emotional", "Storytelling", "Relatable", "Funny", "Professional", "Casual", "Inspirational"] },
      { key: "ContentType", label: "Content Type", hint: "Trending or timeless content?", apiKey: "contentType",
        options: ["Trending", "Evergreen", "Mix of Both Trending and Evergreen"] },
      { key: "CTA", label: "Call-to-Action", hint: "What action do you want users to take?", apiKey: "callToAction",
        options: ["Like", "Share", "Comment", "Visit Website", "Join Group", "Sign Up", "Send Message", "Learn More", "Shop Now", "Watch More", "RSVP"] },
      { key: "TargetAudiance", label: "Target Audience", hint: "Who are you trying to reach?", apiKey: "targetAudience",
        options: ["Gen Z (13-24)", "Millennials (25-40)", "Gen X (41-56)", "Teenagers (13-19)", "Young Adults (20-29)", "Adults (30-45)", "Middle-aged Adults (45-60)", "Parents", "College Students", "Working Professionals", "Travel Enthusiasts", "Fitness Buffs", "Tech Lovers", "Fashion Enthusiasts", "Foodies"] },
    ],
    keywordsLabel: "Topics & Keywords",
    keywordsApiKey: "topicsAndKeywords",
    parseResponse: (data) => ({
      ideas: { title: "Post Ideas", icon: "lightbulb", items: (data.facebookData?.postIdeasList?.postIdeas || []).map(i => ({ title: String(i.postIdea || ""), body: String(i.script || ""), note: String(i.whyThisWorks || "") })) },
      headlines: { title: "Headlines & Descriptions", icon: "title", items: (data.facebookData?.headlinesAndDesList?.headlinesAndDes || []).map(i => ({ title: String(i.headlines || ""), body: String(i.description || "") })) },
      hashtags: { title: "Hashtags", icon: "tag", tags: (data.facebookData?.hashtagsList?.hashtags || []).map(h => typeof h === "string" ? h : String(h.hashtag || JSON.stringify(h))) },
      features: { title: "Engagement Features", icon: "bolt", list: (data.facebookData?.engagementFeatureList?.features || []).map(f => typeof f === "string" ? f : String(f.engagementFeatures || JSON.stringify(f))) },
      boosting: { title: "Boosting Tips", icon: "rocket_launch", items: (data.facebookData?.adAndBoostingList?.boostingTips || []).map(b => ({ title: String(b.adFormat || ""), body: String(b.boosting || "") })) },
      timing: { title: "Best Posting Time", icon: "schedule", list: (data.facebookData?.postingTimeList?.postingTimes || []).map(t => typeof t === "string" ? t : String(t.postingTime || JSON.stringify(t))) },
    }),
  },

  instagram: {
    name: "Instagram",
    slug: "instagram",
    icon: "photo_camera",
    gradient: "from-purple-600 via-pink-500 to-orange-400",
    accentColor: "pink",
    tagline: "Create highly effective Instagram posts tailored to your specific needs and audience.",
    apiEndpoint: "https://maya-backend-service-326007673689.asia-southeast1.run.app/api/content/instagram/insta_prime",
    fields: [
      { key: "ContentGoal", label: "Content Goal", hint: "What do you want to achieve?", apiKey: "contentGoal",
        options: ["Engagement", "Brand Awareness", "Follower Growth", "Website Traffic", "Community Building", "Sales/Conversions", "Educate Audience", "Entertain"] },
      { key: "NicheIndustry", label: "Niche / Industry", hint: "Which niche are you targeting?", apiKey: "niche",
        options: ["Lifestyle", "Fashion & Beauty", "Fitness", "Food & Cooking", "Travel", "Technology", "Education", "Business", "Art & Design", "Music", "Health & Wellness", "Parenting", "Photography"] },
      { key: "ContentType", label: "Content Type", hint: "What format will your post take?", apiKey: "contentType",
        options: ["Reel", "Carousel", "Single Image", "Story", "Live", "Guide", "IGTV"] },
      { key: "ToneStyle", label: "Tone & Style", hint: "What tone should your content have?", apiKey: "toneStyle",
        options: ["Entertaining", "Educational", "Inspirational", "Humorous", "Relatable", "Aesthetic", "Professional", "Raw & Authentic"] },
      { key: "TrendingorEvergreen", label: "Trending or Evergreen", hint: "News-based or timeless?", apiKey: "trendingOrEvergreen",
        options: ["Trending", "Evergreen", "Mix of Both"] },
      { key: "CTA", label: "Call-to-Action", hint: "What action do you want?", apiKey: "callToAction",
        options: ["Follow", "Like", "Comment", "Share", "Save", "Visit Link in Bio", "DM for Details", "Tag a Friend", "Try This"] },
      { key: "TargetAudiance", label: "Target Audience", hint: "Who are you reaching?", apiKey: "targetAudience",
        options: ["Gen Z (13-24)", "Young Adults (20-29)", "Millennials (25-40)", "Women (18-35)", "Men (18-35)", "Fitness Enthusiasts", "Foodies", "Travel Lovers", "Fashion Enthusiasts", "Tech Savvy"] },
    ],
    keywordsLabel: "Keywords & Topics",
    keywordsApiKey: "keywords",
    parseResponse: (data) => ({
      ideas: { title: "Content Ideas", icon: "lightbulb", items: (data.contentIdeaData?.contentIdeaList?.contentIdeas || []).map(i => ({ title: String(i.contentIdea || i.idea || ""), body: String(i.script || i.description || ""), note: i.whyThisWorks ? String(i.whyThisWorks) : "" })) },
      headlines: { title: "Captions", icon: "edit_note", items: (data.contentIdeaData?.captionList?.captions || []).map(c => ({ title: String(c.caption || c.title || ""), body: String(c.description || "") })) },
      hashtags: { title: "Hashtags", icon: "tag", tags: (data.contentIdeaData?.hashtagsList?.hashtags || []).map(h => typeof h === "string" ? h : String(h.hashtag || JSON.stringify(h))) },
      features: { title: "Design & Aesthetic Tips", icon: "palette", list: (data.contentIdeaData?.designAndAestheticList?.designTips || []).map(d => typeof d === "string" ? d : String(d.designTip || d.tip || JSON.stringify(d))) },
      boosting: { title: "Engagement Strategies", icon: "trending_up", list: (data.contentIdeaData?.engagementStrategiesList?.engagementStrategies || []).map(e => typeof e === "string" ? e : String(e.engagementStrategy || e.strategy || JSON.stringify(e))) },
      timing: { title: "Best Posting Time", icon: "schedule", list: (data.contentIdeaData?.postingTimeList?.bestPostTimes || []).map(t => typeof t === "string" ? t : String(t.bestPostTime || t.postingTime || JSON.stringify(t))) },
    }),
  },

  tiktok: {
    name: "TikTok",
    slug: "tiktok",
    icon: "music_note",
    gradient: "from-gray-900 via-pink-500 to-cyan-400",
    accentColor: "cyan",
    tagline: "Create viral TikTok content tailored to your specific niche and audience.",
    apiEndpoint: "https://maya-backend-service-326007673689.asia-southeast1.run.app/api/content/tiktok/tt_prime",
    fields: [
      { key: "VideoGoal", label: "Video Goal", hint: "What's the purpose of this video?", apiKey: "videoGoal",
        options: ["Increase Followers", "Go Viral", "Drive Sales", "Educate Audience", "Build Community", "Promote Brand", "Entertainment", "Collaboration"] },
      { key: "NicheIndustry", label: "Niche / Industry", hint: "What's your content niche?", apiKey: "niche",
        options: ["Lifestyle Vlogs", "Comedy & Skits", "Dance & Music", "Beauty & Fashion", "Fitness", "Food & Cooking", "Education", "Tech Reviews", "DIY & Crafts", "Gaming", "Pets & Animals", "Travel"] },
      { key: "VideoFormat", label: "Video Format", hint: "What style of video?", apiKey: "videoFormat",
        options: ["Mini Vlog", "Tutorial", "Lip Sync", "Transition Video", "Stitch/Duet", "Storytime", "Challenge", "POV", "GRWM", "Before & After"] },
      { key: "ToneStyle", label: "Tone & Style", hint: "What vibe should it have?", apiKey: "toneAndStyle",
        options: ["Playful & Trendy", "Educational", "Dramatic", "Aesthetic", "Raw & Unfiltered", "Comedic", "Motivational", "Relatable"] },
      { key: "ContentType", label: "Content Type", hint: "Trending or timeless?", apiKey: "contentType",
        options: ["Trending", "Evergreen", "Mix of Both"] },
      { key: "CTA", label: "Call-to-Action", hint: "What action to drive?", apiKey: "callToAction",
        options: ["Follow for Part 2", "Like & Share", "Duet This", "Comment Your Answer", "Try This Trend", "Link in Bio", "Save for Later", "Tag a Friend"] },
      { key: "TargetAudiance", label: "Target Audience", hint: "Who's watching?", apiKey: "targetAudience",
        options: ["Gen Z (18–25)", "Gen Alpha (13–17)", "Young Millennials (25–32)", "Content Creators", "Students", "Fitness Community", "Beauty Enthusiasts", "Gamers"] },
    ],
    keywordsLabel: "Sounds & Effects",
    keywordsApiKey: "soundsAndEffects",
    parseResponse: (data) => ({
      ideas: { title: "Video Ideas", icon: "videocam", items: (data.VideoIdeasData?.videoIdeaList?.videoIdeas || []).map(i => ({ title: String(i.videoIdea || i.idea || ""), body: String(i.script || i.description || ""), note: i.whyThisWorks ? String(i.whyThisWorks) : "" })) },
      headlines: { title: "Hooks & Captions", icon: "edit_note", items: (data.VideoIdeasData?.hooksAndCaptionsList?.hooksAndCaptions || []).map(h => ({ title: String(h.hooks || h.hook || h.title || ""), body: String(h.captions || h.caption || h.description || "") })) },
      hashtags: { title: "Hashtags", icon: "tag", tags: (data.VideoIdeasData?.hashtagsList?.hashtags || []).map(h => typeof h === "string" ? h : String(h.hashtag || JSON.stringify(h))) },
      features: { title: "Music & Effects", icon: "music_note", list: (data.VideoIdeasData?.musicAndEffetList?.musicAndEffets || []).map(m => typeof m === "string" ? m : (m.music && m.effects ? `🎵 ${m.music} + ✨ ${m.effects}` : String(m.musicAndEffet || JSON.stringify(m)))) },
      boosting: { title: "Engagement Tactics", icon: "bolt", list: (data.VideoIdeasData?.engagementTacticList?.engagementTactics || []).map(e => typeof e === "string" ? e : String(e.engagementTactic || JSON.stringify(e))) },
      timing: { title: "Best Posting Time", icon: "schedule", list: (data.VideoIdeasData?.postingTimeList?.postingTimes || []).map(t => typeof t === "string" ? t : String(t.postingTime || JSON.stringify(t))) },
    }),
  },

  youtube: {
    name: "YouTube",
    slug: "youtube",
    icon: "play_circle",
    gradient: "from-red-600 to-orange-500",
    accentColor: "red",
    tagline: "Create highly effective YouTube content tailored to your specific niche and audience.",
    apiEndpoint: "https://maya-backend-service-326007673689.asia-southeast1.run.app/api/content/youtube/yt_prime",
    fields: [
      { key: "VideoGoal", label: "Video Goal", hint: "What's the purpose of this video?", apiKey: "videoGoal",
        options: ["Grow Subscriber Base", "Increase Watch Time", "Drive Website Traffic", "Monetization", "Build Authority", "Educate Audience", "Entertain", "Product Review"] },
      { key: "NicheIndustry", label: "Niche / Industry", hint: "What's your channel niche?", apiKey: "niche",
        options: ["Education & How-Tos", "Tech Reviews", "Gaming", "Vlogging", "Finance & Business", "Health & Fitness", "Cooking & Food", "Travel", "Music & Art", "Comedy & Entertainment", "Science & Technology", "Motivation & Self-Help"] },
      { key: "VideoType", label: "Video Type", hint: "What format?", apiKey: "videoType",
        options: ["Tutorial/How-To", "Review", "Listicle", "Vlog", "Short Film", "Interview", "Commentary", "Shorts", "Live Stream", "Documentary Style"] },
      { key: "ToneStyle", label: "Tone & Style", hint: "What tone should it have?", apiKey: "toneAndStyle",
        options: ["Educational & Clear", "Entertaining & Fun", "Professional", "Conversational", "Dramatic", "Inspiring", "Humorous", "Analytical"] },
      { key: "ContentType", label: "Content Type", hint: "Trending or evergreen?", apiKey: "contentType",
        options: ["Trending", "Evergreen", "Mix of Both"] },
      { key: "CTA", label: "Call-to-Action", hint: "What action to drive?", apiKey: "callToAction",
        options: ["Subscribe & Hit Bell Icon", "Like & Comment", "Check Description Links", "Share with Friends", "Join Membership", "Watch Next Video", "Download Resource", "Leave a Review"] },
      { key: "TargetAudiance", label: "Target Audience", hint: "Who's watching?", apiKey: "targetAudience",
        options: ["Young Professionals (25–34)", "Students (16–24)", "Tech Enthusiasts", "Entrepreneurs", "Parents", "Gamers", "Fitness Community", "Creative Professionals", "Hobbyists"] },
    ],
    keywordsLabel: "Keywords & SEO Tags",
    keywordsApiKey: "keywordsAndSeoTags",
    parseResponse: (data) => ({
      ideas: { title: "Video Ideas", icon: "videocam", items: (data.VideoIdeasData?.videoIdeaList?.videoIdeas || []).map(i => ({ title: String(i.videoIdea || i.idea || ""), body: String(i.script || i.description || ""), note: i.whyThisWorks ? String(i.whyThisWorks) : "" })) },
      headlines: { title: "SEO Titles", icon: "search", items: (data.VideoIdeasData?.seoList?.seoTitles || []).map(s => ({ title: String(s.seotitle || s.seoTitle || s.title || ""), body: String(s.description || "") })) },
      hashtags: { title: "Hashtags & Tags", icon: "tag", tags: (data.VideoIdeasData?.hashtagList?.hashtags || []).map(h => typeof h === "string" ? h : String(h.hashtag || JSON.stringify(h))) },
      features: { title: "Thumbnail & Branding", icon: "image", list: (data.VideoIdeasData?.thumbnailAndBrandingList?.thumbnailAndBrandings || []).map(t => typeof t === "string" ? t : String(t.thumbnailAndBranding || JSON.stringify(t))) },
      boosting: { title: "Engagement Tips", icon: "trending_up", list: (data.VideoIdeasData?.engagementList?.engagements || []).map(e => typeof e === "string" ? e : String(e.engagementTips || e.engagement || JSON.stringify(e))) },
      timing: { title: "Best Posting Time", icon: "schedule", list: (data.VideoIdeasData?.postingTimeList?.postingTimes || []).map(t => typeof t === "string" ? t : String(t.postingTime || JSON.stringify(t))) },
    }),
  },

  snapchat: {
    name: "Snapchat",
    slug: "snapchat",
    icon: "photo_camera_front",
    gradient: "from-yellow-400 to-yellow-300",
    accentColor: "yellow",
    tagline: "Create engaging Snapchat stories tailored to your audience and brand.",
    apiEndpoint: "https://maya-backend-service-326007673689.asia-southeast1.run.app/api/content/snapchat/sc_prime",
    fields: [
      { key: "SnapGoal", label: "Snap Goal", hint: "What's the purpose?", apiKey: "snapGoal",
        options: ["Storytelling", "Brand Awareness", "Drive Traffic", "Engagement", "Product Showcase", "Behind-the-Scenes", "Flash Sales", "Event Coverage"] },
      { key: "NicheIndustry", label: "Niche / Industry", hint: "What's your niche?", apiKey: "niche",
        options: ["Events", "Fashion", "Food", "Fitness", "Travel", "Music", "Comedy", "Beauty", "Tech", "Lifestyle", "Sports", "Education"] },
      { key: "StoryType", label: "Story Type", hint: "What kind of story?", apiKey: "storyType",
        options: ["Behind-the-Scenes", "Day in the Life", "Tutorial", "Q&A", "Countdown", "Sneak Peek", "Takeover", "Challenge"] },
      { key: "ToneStyle", label: "Tone & Style", hint: "What vibe?", apiKey: "toneAndStyle",
        options: ["Playful", "Casual", "Exclusive", "Urgent", "Fun & Quirky", "Professional", "Authentic", "Energetic"] },
      { key: "ContentType", label: "Content Type", hint: "Trending or evergreen?", apiKey: "contentType",
        options: ["Trending", "Evergreen", "Mix of Both"] },
      { key: "CTA", label: "Call-to-Action", hint: "What action to drive?", apiKey: "callToAction",
        options: ["Try This Filter", "Swipe Up", "Screenshot This", "Reply to Story", "Add Me", "Share with Friends", "Tap to See More", "Send a Snap"] },
      { key: "TargetAudiance", label: "Target Audience", hint: "Who's watching?", apiKey: "targetAudience",
        options: ["18–24", "13–17", "25–30", "Students", "Gen Z", "Party Goers", "Trendsetters", "Local Community"] },
    ],
    keywordsLabel: "Stickers & Filters",
    keywordsApiKey: "stickersAndFilters",
    parseResponse: (data) => ({
      ideas: { title: "Story Ideas", icon: "auto_stories", items: (data.StoryIdeasData?.storyIdeaList?.storyIdeas || []).map(i => ({ title: String(i.storyIdea || ""), body: String(i.script || ""), note: i.whyThisWorks ? String(i.whyThisWorks) : "" })) },
      headlines: { title: "Text Overlays", icon: "text_fields", items: (data.StoryIdeasData?.textOverlaysList?.overlays || []).map(o => ({ title: String(o.textOverlays || o.overlay || o.textOverlay || ""), body: "" })) },
      hashtags: { title: "Lenses & Filters", icon: "filter_vintage", tags: (data.StoryIdeasData?.lensesAndFiltersList?.lensesAndFilters || []).map(l => typeof l === "string" ? l : String(l.lensesAndFilters || l.lensOrFilter || JSON.stringify(l))) },
      features: { title: "Engagement Features", icon: "bolt", list: (data.StoryIdeasData?.engagementFeaturesList?.engagementFeatures || []).map(e => typeof e === "string" ? e : String(e.engagementFeatures || e.engagementFeature || JSON.stringify(e))) },
      boosting: { title: "Boosting Tips", icon: "rocket_launch", list: (data.StoryIdeasData?.boostingTipsList?.boostingTips || []).map(b => typeof b === "string" ? b : String(b.boostingTips || b.boostingTip || JSON.stringify(b))) },
      timing: { title: "Best Posting Time", icon: "schedule", list: (data.StoryIdeasData?.postingTimeList?.postingTime || []).map(t => typeof t === "string" ? t : String(t.postingTime || JSON.stringify(t))) },
    }),
  },

  pinterest: {
    name: "Pinterest",
    slug: "pinterest",
    icon: "push_pin",
    gradient: "from-red-500 to-red-400",
    accentColor: "red",
    tagline: "Create high-performing Pinterest pins tailored to your niche and audience.",
    apiEndpoint: "https://maya-backend-service-326007673689.asia-southeast1.run.app/api/content/pinterest/pin_prime",
    fields: [
      { key: "PinGoal", label: "Pin Goal", hint: "What's the purpose of this pin?", apiKey: "pinGoal",
        options: ["Drive Website Traffic", "Increase Saves", "Brand Awareness", "Product Sales", "Grow Followers", "Inspire & Educate", "Lead Generation", "Build Board Authority"] },
      { key: "NicheIndustry", label: "Niche / Industry", hint: "What's your niche?", apiKey: "niche",
        options: ["DIY & Crafts", "Home Decor", "Fashion & Style", "Food & Recipes", "Fitness & Health", "Travel", "Business & Marketing", "Wedding & Events", "Education", "Art & Design", "Parenting", "Technology"] },
      { key: "PinType", label: "Pin Type", hint: "What format?", apiKey: "pinType",
        options: ["Single Image Pin", "Video Pin", "Idea Pin", "Carousel Pin", "Infographic", "Product Pin", "Step-by-Step", "Quote Pin"] },
      { key: "ToneStyle", label: "Tone & Style", hint: "What aesthetic?", apiKey: "toneAndStyle",
        options: ["Clean & Aesthetic", "Bold & Eye-catching", "Minimal", "Warm & Cozy", "Professional", "Playful", "Luxurious", "Educational"] },
      { key: "ContentType", label: "Content Type", hint: "Trending or evergreen?", apiKey: "contentType",
        options: ["Trending", "Evergreen", "Seasonal", "Mix of Both"] },
      { key: "CTA", label: "Call-to-Action", hint: "What action to drive?", apiKey: "callToAction",
        options: ["Save This Idea", "Click to Read More", "Shop Now", "Try This Recipe", "Get the Tutorial", "Visit Website", "Follow for More", "Pin for Later"] },
      { key: "TargetAudiance", label: "Target Audience", hint: "Who's pinning?", apiKey: "targetAudience",
        options: ["Millennial Women (25–40)", "Home Makers", "DIY Enthusiasts", "Brides-to-Be", "Entrepreneurs", "Students", "Foodies", "Interior Design Lovers", "Fashion Followers"] },
    ],
    keywordsLabel: "Search Keywords",
    keywordsApiKey: "searchKeywords",
    parseResponse: (data) => ({
      ideas: { title: "Pin Ideas", icon: "lightbulb", items: (data.PinIdeasData?.pinIdeaList?.pinIdeas || []).map(i => ({ title: String(i.pinIdea || i.idea || ""), body: String(i.script || i.description || ""), note: i.whyThisWorks ? String(i.whyThisWorks) : "" })) },
      headlines: { title: "Titles & Descriptions", icon: "title", items: (data.PinIdeasData?.titleAndDescriptionList?.titleAndDescriptions || []).map(t => ({ title: String(t.title || ""), body: String(t.description || "") })) },
      hashtags: { title: "Hashtags", icon: "tag", tags: (data.PinIdeasData?.hashtagList?.hashtags || []).map(h => typeof h === "string" ? h : String(h.hashtag || JSON.stringify(h))) },
      features: { title: "Aesthetic & Design Tips", icon: "palette", list: (data.PinIdeasData?.aestheticAndDesignList?.aestheticAndDesigns || []).map(a => typeof a === "string" ? a : String(a.aestheticAndDesign || JSON.stringify(a))) },
      boosting: { title: "Engagement Tips", icon: "trending_up", list: (data.PinIdeasData?.engagementList?.engagements || []).map(e => typeof e === "string" ? e : String(e.engagement || JSON.stringify(e))) },
      timing: { title: "Best Posting Time", icon: "schedule", list: (data.PinIdeasData?.postingTimeList?.postingTimes || []).map(t => typeof t === "string" ? t : String(t.postingTime || JSON.stringify(t))) },
    }),
  },
};
